### ISSUE TITLE
Tell me about this:

### ISSUE THREAD

**Issue by OfficialAudite** [InKahootz/SteamInventoryHelper#2]
https://www.reddit.com/r/GlobalOffensive/comments/70xofs/warning_trusted_steam_inventory_helper_now/

**Comment by Luckz** [comment]
That's why this repository exists, https://www.reddit.com/r/GlobalOffensive/comments/70xofs/warning_trusted_steam_inventory_helper_now/dn722d2/

**Comment by hymccord** [comment]
Hi and thank you for raising the question!

This repository was created just before SIH changes permissions to run on ALL urls, thus enabling the developers to monitor basically everything you do.

I implore you to explore the repository yourself, but I will point you directly to the only file you need to look at: [manifest.json](https://github.com/InKahootz/SteamInventoryHelper/blob/master/manifest.json). Specifically, you want to look at [line 86](https://github.com/InKahootz/SteamInventoryHelper/blob/218e5e6ef1632c352749ec75948a40be3c1bd8fb/manifest.json#L86). This is where extensions request their permissions. Read more about permission warnings [here](https://developer.chrome.com/extensions/permission_warnings).

The devs added a permission for `<all_urls>` which notified that the devs wanted **Read and modify all your data on all websites you visit**, causing the reddit OP to look into it further. 

The last version before spam town is the one stored in this repository.

**Comment by hymccord** [comment]
Just to follow up on this. I downloaded the latest version from the chrome store to look at the permissions.

v1.11.8.1
```
  "permissions": [
    "notifications",
    "alarms",
    "storage",
    "background",
    "webRequest",
    "webRequestBlocking",
    "activeTab",
    "<all_urls>"
  ],
```

This repo
v1.11.4.2

```
"permissions":[  
   "notifications",
   "alarms",
   "storage",
   "background",
   "webRequest",
   "webRequestBlocking",
   "*://steamcommunity.com/*",
   "*://*.steampowered.com/*",
   "http://*.steamstatic.com/*",
   "*://steamrep.com/*",
   "*://steamcdn-a.akamaihd.net/*"
],
```
