### ISSUE TITLE
Messages file is missing for locale

### ISSUE THREAD

**Issue by MarvashMagalli** [InKahootz/SteamInventoryHelper#8]
Hello, I'll start off with saying that I don't know how any of this works, so if this is an error unrelated to the extension, I'm sorry.
I've been using it for a while, until it suddenly stopped working. I tried loading it again, but now I get this message from Chrome:
"Messages file is missing for locale."
How do I solve this problem? Thanks in advance.

**Comment by KaimTime** [comment]
heya! not the creator but I had the same issue; turns out just deleting the locale mentioned in the error (mine was the "_locales/no" folder) fixes it & you can load the plugin from there!

**Comment by MarvashMagalli** [comment]
That solution worked, thanks a lot!
